#!/usr/bin/python
# *-* coding: utf-8 *-*
# Author: Thomas Martin <thomas.martin.1@ulaval.ca>
# File: orbdb

## Copyright (c) 2010-2018 Thomas Martin <thomas.martin.1@ulaval.ca>
## 
## This file is part of ORBDB
##
## ORBDB is free software: you can redistribute it and/or modify it
## under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## ORBDB is distributed in the hope that it will be useful, but WITHOUT
## ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
## or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
## License for more details.
##
## You should have received a copy of the GNU General Public License
## along with ORBDB.  If not, see <http://www.gnu.org/licenses/>.

#############################################
############ ORBDB script ###################
#############################################

# Manage and use ORB files database

import sys, os
from orbdb.core import OrbDB
import orbdb.core
import argparse
from argparse import ArgumentParser
from orb.core import Logger

def main(args):
    Logger().start_logging()
    
    db = OrbDB(args.db_name)
    
    if args.subparser_name == 'append':
        if os.path.exists(args.append_list_path):
            db.append(args.append_list_path, args.force)
        else:
            print "Error: List file '{}' does not exist".format(
                args.append_list_path)
            sys.exit(2)

    if args.subparser_name == 'clean':
        check_yes = raw_input("Are you sure you want to clean the database ?\n type 'yes I want to clean the database': ")
        if check_yes == 'yes I want to clean the database':
            db.clean()
        else: print 'phiuu'

    if args.subparser_name == 'list-between':
        db.list_between(args.odo1, args.odo2)
        
    if args.subparser_name == 'print':
        keywords = 'OBJECT FILTER RUNID PI_NAME SITSTEP'
        db.print_rows(keywords.split())

    if args.subparser_name == 'keys':
        for key in db.get_keys():
            print key
       
    

if __name__ == "__main__":

    parser = ArgumentParser(
        version=('ORB-version {}'.format(
            orbdb.core.__version__)),
        description="Manage and use a database of FITS files. This was created primarily to list and sort SITELLE's image files")

    parser.add_argument('db_name', help='Path to the database')


    subparsers = parser.add_subparsers(help='operation type', dest='subparser_name')

    parser_append = subparsers.add_parser('append', help='Append new files')
    parser_append.add_argument('append_list_path',
                               help='Path to a list of files to append')
    
    parser_append.add_argument('--force', dest='force',
                               default=False,
                               action='store_true',
                               help='Force update')
    
    
    subparsers.add_parser('clean', help='Clean database')

    subparsers.add_parser('print', help='Print all basic keywords (OBJECT FILTER RUNID SITSTEP)')

    between = subparsers.add_parser('list-between', help='List scans between two odometers')
    between.add_argument('odo1', help='first odometer', type=int)
    between.add_argument('odo2', help='last odometer', type=int)
    
    
    
    args = parser.parse_args()
    
    main(args)
